version: "2.4"
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.0
    healthcheck:
      test: "curl http://localhost:9200/_cluster/health"
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms128m -Xmx128m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    ports:
      - "9202:9200"
  elasticsearch_seeder:
    image: curlimages/curl:7.83.1
    depends_on:
      elasticsearch:
        condition: service_healthy
    volumes:
      - ./elasticsearch_init.sh:/elasticsearch_init.sh
    entrypoint: sh -c "ES_HOST=http://elasticsearch:9200 /elasticsearch_init.sh"
  kuliner-api:
    build:
      context: ../
      dockerfile: ./build/package/kuliner-api/Dockerfile
    depends_on:
      elasticsearch_seeder:
        condition: service_completed_successfully
    environment:
      - ES_HOST=http://elasticsearch:9200
    ports:
      - 8101:8101
